version: "3"

services:
  db:
    image: mysql:5
    container_name: remember_db
    environment:
      MYSQL_DATABASE: dataname
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "3307:3306" # 将3306映射到3307, 供其他容器使用

  web:
    build: .
    container_name: remember_web
    volumes:
      - .:/usr/src/app
    command: sh setup.sh
    depends_on:
      - db
    links:
      - db
    restart: always

  nginx:
    build: ./nginx
    container_name: remember_nginx
    ports:
      - "80:80"
    volumes:
      - ./static:/usr/share/nginx/html/static
      - ./media:/usr/share/nginx/html/media
    links:
      - web
    depends_on:
      - web
    restart: always

volumes:
  data: